// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4as_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4jf_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4norm_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4sas_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4sn_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4st_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4t_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4as_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4as_mod, 0},
    {"_rcpp_module_boot_stan_fit4jf_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4jf_mod, 0},
    {"_rcpp_module_boot_stan_fit4norm_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4norm_mod, 0},
    {"_rcpp_module_boot_stan_fit4sas_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4sas_mod, 0},
    {"_rcpp_module_boot_stan_fit4sn_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4sn_mod, 0},
    {"_rcpp_module_boot_stan_fit4st_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4st_mod, 0},
    {"_rcpp_module_boot_stan_fit4t_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4t_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_flexmeta(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
