#' The 'flexmeta' package.
#'
#' @description A R package for implementing meta-analysis using flexible
#' random-effects distribution models (e.g., skew t-distribution,
#' sinh-arcsinh distribution).
#'
#' @docType package
#' @name flexmeta-package
#' @aliases flexmeta
#' @useDynLib flexmeta, .registration = TRUE
#' @import methods rstantools Rcpp
#' @importFrom rstan sampling
#'
#' @references
#' Stan Development Team (2019).
#' RStan: the R interface to Stan.
#' R package version 2.19.2.
#' \url{https://mc-stan.org}
#'
#' Azzalini, A. (1985).
#' A class of distributions which includes the normal ones.
#' \emph{Scand. J. Statist.}
#' \strong{12}(2): 171-178.
#'
#' Azzalini, A. (1986).
#' Further results on a class of distributions which includes the normal ones.
#' \emph{Statistica.}
#' \strong{46}(2): 199-208.
#'
#' Azzalini, A. and Capitanio, A. (2003).
#' Distributions generated by perturbation of symmetry with emphasis on a multivariate skew-t distribution.
#' \emph{J. Roy. Statist. Soc. B.}
#' \strong{65}(2): 367–389.
#' \url{https://doi.org/10.1111/1467-9868.00391}
#'
#' Azzalini, A. and Capitanio, A. (2014).
#' \emph{The Skew-Normal and Related Families.}
#' Cambridge: Cambridge University Press.
#'
#' Jones, M. C. and Faddy, M. J. (2003).
#' A skew extension of the t-distribution, with applications.
#' \emph{J. Roy. Statist. Soc. B.}
#' \strong{65}(1): 159–174.
#' \url{https://doi.org/10.1111/1467-9868.00378}
#'
#' Jones, M. C. and Pewsey, A. (2009).
#' Sinh-arcsinh distributions.
#' \emph{Biometrika.}
#' \strong{96}(4): 761-780.
#' \url{https://doi.org/10.1093/biomet/asp053}
NULL
